name: Stage S3

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Upload to S3
        run: |
          aws s3 sync dist/ s3://sandbox-react-vite-test --region eu-north-1 --delete
        env:
          AWS_S3_BUCKET: sandbox-react-vite-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
